### ISSUE TITLE
如果自己的业务后台tcp地址是  ip:port+自定义的路由  这种格式的该怎么办？

### ISSUE THREAD

**Issue by SRellopn** [WuKongIM/WuKongIMAndroidSDK#2]
getIpAndPort方法只能是ip:port这个格式的返回，port这个字段不能是字符串类型的。
遇到自定义的地址该怎么处理呢？

**Comment by tangtaoit** [comment]
没理解，可以举例说明吗

**Comment by SRellopn** [comment]
自己的业务/route返回的地址是这样的：
`{
    "tcp_addr": "10.10.12.243:10082/r/v1/im",
    "ws_addr": "ws://10.10.12.243:5200",
    "wss_addr": ""
}`
安卓sdk的方法是
![83b3e7cfc01953819429e7cbcdd83db](https://github.com/WuKongIM/WuKongIMAndroidSDK/assets/156177043/310743eb-4d4f-43ef-8d98-29d6f35e3f9f)
`andPortListener.onGetSocketIpAndPort(strings[0], strings[1].toInt())`这个方法第二个参数只能接受int类型的参数。而我们自己的tpc_addr是有路由参数的。请问这样的情况有什么好的处理方法吗？

**Comment by tangtaoit** [comment]
tcp还有路由参数？第一次见，你确定你们没弄错？ android的底层库也不支持route参数，服务器也不支持route

**Comment by SRellopn** [comment]
如果im部署到服务器上，通过nginx反向代理的话，会有路由参数。比如网站域名是www.test.com,那么im的服务经过nginx反向代理后就会是(举个同步会话列表的例子)：https://www.test.com/im/conversation/sync。相应的/route返回的就应该是：
`{ "tcp_addr": "https://www.test.com/im", "ws_addr": "ws://www.test.com/im/ws", "wss_addr": "wss://www.test.com/im/ws" }`.

**Comment by tangtaoit** [comment]
> 如果im部署到服务器上，通过nginx反向代理的话，会有路由参数。比如网站域名是www.test.com,那么im的服务经过nginx反向代理后就会是(举个同步会话列表的例子)：[https://www.test.com/im/conversation/sync。相应的/route返回的就应该是：](https://www.test.com/im/conversation/sync%E3%80%82%E7%9B%B8%E5%BA%94%E7%9A%84/route%E8%BF%94%E5%9B%9E%E7%9A%84%E5%B0%B1%E5%BA%94%E8%AF%A5%E6%98%AF%EF%BC%9A) `{ "tcp_addr": "https://www.test.com/im", "ws_addr": "ws://www.test.com/im/ws", "wss_addr": "wss://www.test.com/im/ws" }`.

你说的是http和ws，这些有path的概念，socket tcp没有 path这些概念的

**Comment by SRellopn** [comment]
> > 如果im部署到服务器上，通过nginx反向代理的话，会有路由参数。比如网站域名是www.test.com,那么im的服务经过nginx反向代理后就会是(举个同步会话列表的例子)：[https://www.test.com/im/conversation/sync。相应的/route返回的就应该是：](https://www.test.com/im/conversation/sync%E3%80%82%E7%9B%B8%E5%BA%94%E7%9A%84/route%E8%BF%94%E5%9B%9E%E7%9A%84%E5%B0%B1%E5%BA%94%E8%AF%A5%E6%98%AF%EF%BC%9A) `{ "tcp_addr": "https://www.test.com/im", "ws_addr": "ws://www.test.com/im/ws", "wss_addr": "wss://www.test.com/im/ws" }`.
> 
> 你说的是http和ws，这些有path的概念，socket tcp没有 path这些概念的
也就是说安卓SDK同步离线信息请求用的是tcp，不是http。
因为这边一开始集成的是js的SDK，想当然的认为安卓的也是和js一样用htpp同步离线消息。

**Comment by SRellopn** [comment]
也就是说安卓SDK同步离线信息请求用的是tcp，不是http。
因为这边一开始集成的是js的SDK，想当然的认为安卓的也是和js一样用htpp同步离线消息。

**Comment by SRellopn** [comment]
也就是说安卓SDK同步离线信息请求用的是tcp，不是http。
因为这边一开始集成的是js的SDK，想当然的认为安卓的也是和js一样用http同步离线消息。

**Comment by SRellopn** [comment]
明白了
